# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87e48d58facf358bcdf67b262a333344d281cedb14bef28fce5659ad1d5fac0fefb3a799e8b97404ed2c0895cde3c96ac6358d8042617037d9ad7b194262a524

test:
  secret_key_base: 7f4a76a3f2345771021e44d8b3ce6cc64baba45e0b3106a144ad0b3cc4857183065ce0175f19a46900692c3f3d9053ee4df37b5142b5552dbb030023b39967dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
